name: viktoriaapp
description: The app for the Viktoriaschule Aachen
version: 2.1.2+34
author: jld3103, fingeg

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  crypto: ^2.1.4
  intl: ^0.16.1
  firebase_messaging: ^6.0.9
  shared_preferences: ^0.5.6+2
  material_design_icons_flutter: ^3.4.4995
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  transparent_image: ^1.0.0
  after_layout: ^1.0.7+2
  timeago: ^2.0.26
  dio: ^3.0.8
  encrypt: ^4.0.0
  js: ^0.6.1+1
  add_2_calendar: ^1.3.1
  flutter_webview_plugin: ^0.3.10+1
  in_app_update: ^1.1.6
  flutter_event_bus: ^0.0.2

dev_dependencies:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Light.ttf
          weight: 100
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Light.ttf
          weight: 200
  assets:
    - images/logo_green.png
    - images/logo_green_192x192.png
    - pubspec.yaml