name: viktoriaapp
description: The app for the Viktoriaschule Aachen
version: 2.1.2+34
author: jld3103, fingeg

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  crypto:
  intl:
  firebase_messaging:
  shared_preferences:
  material_design_icons_flutter:
  cached_network_image: ^2.0.0-rc
  url_launcher:
  share:
  transparent_image:
  after_layout:
  timeago:
  dio:
  version:
  encrypt:
  js:
  google_fonts:
  add_2_calendar:
  webview_flutter:
  in_app_update:

dev_dependencies:
  flutter_launcher_icons:

dependency_overrides:
  google_fonts:
    git:
      url: https://github.com/jld3103/google-fonts-flutter
      ref: fix/web-path_provider

flutter:
  uses-material-design: true
  fonts:
  - family: Ubuntu
    fonts:
      - asset: fonts/Ubuntu-Regular.ttf
      - asset: fonts/Ubuntu-Italic.ttf
        style: italic
      - asset: fonts/Ubuntu-Light.ttf
        weight: 100
      - asset: fonts/Ubuntu-Bold.ttf
        weight: 700
  assets:
    - images/logo_green.png
    - images/logo_green_192x192.png
    - pubspec.yaml