name: calendar

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar:
  material_design_icons_flutter:
  utils:
    path: ../../utils
  widgets:
    path: ../../widgets