name: substitution_plan

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  timeago:
  timetable:
    path: ../timetable
  utils:
    path: ../../utils
  widgets:
    path: ../../widgets