name: viktoriaapp
description: The app for the Viktoriaschule Aachen
version: 2.1.2+34
author: jld3103, fingeg

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter:
  after_layout:
  dio:
  flutter_event_bus:
  aixformation:
    path: ../features/aixformation
  cafetoria:
    path: ../features/cafetoria
  calendar:
    path: ../features/calendar
  substitution_plan:
    path: ../features/substitution_plan
  timetable:
    path: ../features/timetable
  utils:
    path: ../utils
  widgets:
    path: ../widgets

dev_dependencies:
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Light.ttf
          weight: 100
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Light.ttf
          weight: 200
  assets:
    - ../images/logo_green.png
    - ../images/logo_green_192x192.png
    - pubspec.yaml