name: aixformation

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin:
  url_launcher:
  share:
  utils:
    path: ../../utils
  widgets:
    path: ../../widgets