name: widgets

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter:
  flutter_event_bus:
  after_layout:
  dio:
  path_provider:
  utils:
    path: ../utils