name: widgets

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_event_bus:
  after_layout:
  cached_network_image:
  dio:
  path_provider:
  utils:
    path: ../utils