name: frame

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout:
  timeago:
  crypton:
  pointycastle:
  asn1lib:
  utils:
    path: ../utils
  widgets:
    path: ../widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: app.viktoria.schule.frame
    pluginClass: FramePlugin