name: frame

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter:
  after_layout:
  flutter_event_bus:
  utils:
    path: ../utils
  widgets:
    path: ../widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: app.viktoria.schule.frame
    pluginClass: FramePlugin