name: utils

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging:
  js:
  shared_preferences:
  encrypt:
  crypto:
  flutter_event_bus:
  intl:
  dio:
  package_info:
  widgets:
    path: ../widgets